### ISSUE TITLE
Bauble ghost stacks

### ISSUE THREAD

**Issue by anoomolu** [jss2a98aj/Baubles-Expanded#2]
Hiya. I'm using Thaumcraft 4.2.3.5 and BaublesExpanded-2.1.2-1-gf6dea39.dirty.jar.

Shift-clicking a ring into the first ring slot in survival allows you to duplicate it. Tested by going into creative to obtain a few different rings then switching to survival mode. This only happens with the first ring slot, the other slots work as normal.

**Comment by jss2a98aj** [comment]
It appears that those are ghost stacks, but it is still something I need to fix.

**Comment by jss2a98aj** [comment]
This is fixed in 2.1.4
