### ISSUE TITLE
Thaumcraft still download the original Baubles

### ISSUE THREAD

**Issue by song682** [jss2a98aj/Baubles-Expanded#6]
While I use Thaumcraft-1.7.10-4.2.3.5 and BaublesExpanded-2.1.2 , Thauncraft still downloads the original Baubles.

**Comment by jss2a98aj** [comment]
I will likely need to find a different solution to stop it from doing that, as one other person has reported the same.

**Comment by song682** [comment]
> I will likely need to find a different solution to stop it from doing that, as one other person has reported the same

Will be fixed? I'm dying to this function for long.

**Comment by jss2a98aj** [comment]
It will be, but I am going to have to use ASM (will need to ask for help if I do) or add a Mixins dependency.

**Comment by Roadhog360** [comment]
For me if I have Baubles Expanded, Thaumcraft won't try to download the original.

**Comment by song682** [comment]
> For me if I have Baubles Expanded, Thaumcraft won't try to download the original.

Maybe u are right. It seems disappeard right now.
Btw, i mean, use the latest version.

**Comment by Roadhog360** [comment]
@jss2a98aj Seems resolved

**Comment by song682** [comment]
@jss2a98aj It was completely resolved.
